# Kitty Theme (Catppuccin Mocha)
background_opacity 0.8
confirm_os_window_close 0

# Padding makes it look much cleaner
window_padding_width 15

# Font configuration
font_family      family="Maple Mono NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0

# Braille support for vtop/btop graphs
symbol_map U+2800-U+28FF Maple Mono NF

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Green Theme Colors
active_border_color #a6e3a1
inactive_border_color #313244
cursor #a6e3a1
foreground #a6e3a1
active_tab_foreground #11111b
active_tab_background #a6e3a1
inactive_tab_foreground #a6e3a1
inactive_tab_background #1e1e2e

# Green ANSI Colors
color2  #a6e3a1
color10 #a6e3a1
